### ISSUE TITLE
Taboola Ads not appearing

### ISSUE THREAD

**Issue by keshavsharma333** [ahmedkaludi/ads-for-wp#218] opened 2019-07-13 08:43 UTC
https://secure.helpscout.net/conversation/901323874/73527?folderId=3044500

User has taboola ads on his site, which is not showing up on side bar.

It is just showing a blank space.

The Code used is:

<div id="taboola-right-rail-thumbnails"></div>
<script type="text/javascript">
  window._taboola = window._taboola || [];
  _taboola.push({
    mode: 'thumbnails-rr',
    container: 'taboola-right-rail-thumbnails',
    placement: 'Right Rail Thumbnails',
    target_type: 'mix'
  });
</script>

The format is:
![taboola](https://user-images.githubusercontent.com/27533027/61169191-c7020380-a577-11e9-8b45-e349fcf4b446.png)
![taboola1](https://user-images.githubusercontent.com/27533027/61169192-c79a9a00-a577-11e9-9727-ed1a3c42e45a.png)
[taboola code.txt](https://github.com/ahmedkaludi/ads-for-wp/files/3388665/taboola.code.txt)

**Comment by iamkingsleyf** [comment] 2019-07-13 09:00
This is a duplicate of what i opened before 🙄🙄🙄

**Comment by iamkingsleyf** [comment] 2019-07-15 06:19
Alright

**Closed** 2019-07-25 06:37 UTC
Labels: P: HIGH, bug, urgent
